/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    piatti: Piatti;
    'servizi-accessori': ServiziAccessori;
    'menu-fisso': MenuFisso;
    vini: Vini;
    birre: Birre;
    liquori: Liquori;
    cocktail: Cocktail;
    bevande: Bevande;
    allergeni: Allergeni;
    'categoria-menu-fisso': CategoriaMenuFisso;
    'categoria-piatti': CategoriaPiatti;
    'tipologie-vino': TipologieVino;
    'tipologie-birra': TipologieBirra;
    'tipologie-liquore': TipologieLiquore;
    'tipologie-cocktail': TipologieCocktail;
    'tipologie-bevanda': TipologieBevanda;
    nazioni: Nazioni;
    regioni: Regioni;
    zone: Zone;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    piatti: {
      menuFissi: 'menu-fisso';
    };
    'servizi-accessori': {
      menuFissi: 'menu-fisso';
    };
    allergeni: {
      piatti: 'piatti';
    };
    'categoria-menu-fisso': {
      elementi: 'menu-fisso';
    };
    'categoria-piatti': {
      elementi: 'piatti';
    };
  };
  collectionsSelect: {
    piatti: PiattiSelect<false> | PiattiSelect<true>;
    'servizi-accessori': ServiziAccessoriSelect<false> | ServiziAccessoriSelect<true>;
    'menu-fisso': MenuFissoSelect<false> | MenuFissoSelect<true>;
    vini: ViniSelect<false> | ViniSelect<true>;
    birre: BirreSelect<false> | BirreSelect<true>;
    liquori: LiquoriSelect<false> | LiquoriSelect<true>;
    cocktail: CocktailSelect<false> | CocktailSelect<true>;
    bevande: BevandeSelect<false> | BevandeSelect<true>;
    allergeni: AllergeniSelect<false> | AllergeniSelect<true>;
    'categoria-menu-fisso': CategoriaMenuFissoSelect<false> | CategoriaMenuFissoSelect<true>;
    'categoria-piatti': CategoriaPiattiSelect<false> | CategoriaPiattiSelect<true>;
    'tipologie-vino': TipologieVinoSelect<false> | TipologieVinoSelect<true>;
    'tipologie-birra': TipologieBirraSelect<false> | TipologieBirraSelect<true>;
    'tipologie-liquore': TipologieLiquoreSelect<false> | TipologieLiquoreSelect<true>;
    'tipologie-cocktail': TipologieCocktailSelect<false> | TipologieCocktailSelect<true>;
    'tipologie-bevanda': TipologieBevandaSelect<false> | TipologieBevandaSelect<true>;
    nazioni: NazioniSelect<false> | NazioniSelect<true>;
    regioni: RegioniSelect<false> | RegioniSelect<true>;
    zone: ZoneSelect<false> | ZoneSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    generali: Generali;
    'menu-config': MenuConfig;
  };
  globalsSelect: {
    generali: GeneraliSelect<false> | GeneraliSelect<true>;
    'menu-config': MenuConfigSelect<false> | MenuConfigSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piatti".
 */
export interface Piatti {
  id: number;
  /**
   * Se il piatto è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Se il piatto è disponibile solo nei menu fissi (non nel menu pubblico)
   */
  soloMenuFissi?: boolean | null;
  /**
   * Nome del piatto
   */
  nome: string;
  /**
   * Prezzo del piatto (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Categoria del piatto
   */
  categoria: number | CategoriaPiatti;
  /**
   * Descrizione opzionale del piatto
   */
  descrizione?: string | null;
  /**
   * Se il piatto è senza glutine
   */
  glutenFree?: boolean | null;
  /**
   * Se il piatto non contiene uova
   */
  noUovo?: boolean | null;
  /**
   * Se il piatto non contiene latticini
   */
  noLatticini?: boolean | null;
  /**
   * Se il piatto è vegano
   */
  vegan?: boolean | null;
  /**
   * Allergeni presenti nel piatto
   */
  allergeni?: (number | Allergeni)[] | null;
  /**
   * Menu fissi che includono questo piatto (sola lettura)
   */
  menuFissi?: {
    docs?: (number | MenuFisso)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-piatti".
 */
export interface CategoriaPiatti {
  id: number;
  /**
   * Se la categoria è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  nome: string;
  /**
   * Descrizione opzionale della categoria
   */
  descrizione?: string | null;
  /**
   * Elementi associati a questa categoria
   */
  elementi?: {
    docs?: (number | Piatti)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergeni".
 */
export interface Allergeni {
  id: number;
  /**
   * Nome dell'allergene (es. 'Glutine', 'Latte', 'Uova')
   */
  nome: string;
  /**
   * Descrizione opzionale dell'allergene
   */
  descrizione?: string | null;
  /**
   * Elenco dei piatti che contengono questo allergene (sola lettura)
   */
  piatti?: {
    docs?: (number | Piatti)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-fisso".
 */
export interface MenuFisso {
  id: number;
  /**
   * Se il menu è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nome del menu fisso
   */
  nome: string;
  /**
   * Categoria del menu fisso
   */
  categoria: number | CategoriaMenuFisso;
  /**
   * Prezzo del menu fisso (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Descrizione opzionale del menu
   */
  descrizione?: string | null;
  /**
   * Piatti inclusi nel menu
   */
  piatti?: (number | Piatti)[] | null;
  /**
   * Servizi inclusi nel menu
   */
  servizi?: (number | ServiziAccessori)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-menu-fisso".
 */
export interface CategoriaMenuFisso {
  id: number;
  /**
   * Se la categoria è visibile nel menu
   */
  inLista?: boolean | null;
  nome: string;
  /**
   * Descrizione opzionale della categoria
   */
  descrizione?: string | null;
  /**
   * Elementi associati a questa categoria
   */
  elementi?: {
    docs?: (number | MenuFisso)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servizi-accessori".
 */
export interface ServiziAccessori {
  id: number;
  /**
   * Se il servizio è visibile nel menu
   */
  inLista?: boolean | null;
  /**
   * Nome del servizio (es. "Coperto", "Pane e Grissini")
   */
  nome: string;
  /**
   * Prezzo del servizio (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Descrizione opzionale del servizio
   */
  descrizione?: string | null;
  /**
   * Menu fissi che includono questo servizio (sola lettura)
   */
  menuFissi?: {
    docs?: (number | MenuFisso)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vini".
 */
export interface Vini {
  id: number;
  /**
   * Se vino è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nome vino
   */
  nome: string;
  /**
   * Descrizione opzionale vino
   */
  descrizione?: string | null;
  /**
   * Prezzo della bottiglia (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Prezzo per calice (max 10 cifre, 2 decimali)
   */
  prezzoCalice?: number | null;
  /**
   * Tipologia vino
   */
  tipologia: number | TipologieVino;
  /**
   * Grado alcolico (es. "13.5%", "12%")
   */
  grado?: string | null;
  /**
   * Capacità della bottiglia (es. "750ml", "1L")
   */
  capacita?: string | null;
  /**
   * Anno di produzione (es. "2020", "2018", "NV" per non vintage)
   */
  anno?: string | null;
  /**
   * Nome della cantina produttrice
   */
  cantina?: string | null;
  /**
   * Certificazione (es. DOC, DOCG, IGT)
   */
  certificazione?: string | null;
  /**
   * Nazione di produzione
   */
  nazione: number | Nazioni;
  /**
   * Regione di produzione (opzionale)
   */
  regione?: (number | null) | Regioni;
  /**
   * Zona di produzione (opzionale)
   */
  zona?: (number | null) | Zone;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-vino".
 */
export interface TipologieVino {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nazioni".
 */
export interface Nazioni {
  id: number;
  /**
   * Nome della nazione (es. 'Italia', 'Francia')
   */
  nome: string;
  /**
   * Sigla ISO alpha-3 (es. ITA, FRA)
   */
  sigla: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioni".
 */
export interface Regioni {
  id: number;
  /**
   * Nome della regione (es. 'Toscana', 'Piemonte')
   */
  nome: string;
  nazione: number | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zone".
 */
export interface Zone {
  id: number;
  /**
   * Nome della zona (es. 'Chianti', 'Barolo')
   */
  nome: string;
  /**
   * Per facilitare le query
   */
  nazione: number | Nazioni;
  regione: number | Regioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birre".
 */
export interface Birre {
  id: number;
  /**
   * Se birra è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nome birra
   */
  nome: string;
  /**
   * Descrizione opzionale birra
   */
  descrizione?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Tipologia birra
   */
  tipologia: number | TipologieBirra;
  /**
   * Grado alcolico (es. "5.2%", "4.5%")
   */
  grado?: string | null;
  /**
   * Capacità (es. "33cl", "50cl", "1L")
   */
  capacita?: string | null;
  /**
   * Nazione di produzione
   */
  nazione: number | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-birra".
 */
export interface TipologieBirra {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liquori".
 */
export interface Liquori {
  id: number;
  /**
   * Se liquore è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nome liquore
   */
  nome: string;
  /**
   * Descrizione opzionale liquore
   */
  descrizione?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Tipologia liquore
   */
  tipologia: number | TipologieLiquore;
  /**
   * Grado alcolico (es. "40%", "35%")
   */
  grado?: string | null;
  /**
   * Capacità (es. "50ml", "70cl", "1L")
   */
  capacita?: string | null;
  /**
   * Invecchiamento (es. "12 anni", "8 mesi", "Non invecchiato")
   */
  invecchiamento?: string | null;
  /**
   * Nazione di produzione
   */
  nazione: number | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-liquore".
 */
export interface TipologieLiquore {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail".
 */
export interface Cocktail {
  id: number;
  /**
   * Se cocktail è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nome cocktail
   */
  nome: string;
  /**
   * Descrizione opzionale cocktail
   */
  descrizione?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Tipologia cocktail
   */
  tipologia: number | TipologieCocktail;
  /**
   * Nazione di origine del cocktail
   */
  nazione?: (number | null) | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-cocktail".
 */
export interface TipologieCocktail {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bevande".
 */
export interface Bevande {
  id: number;
  /**
   * Se bevanda è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nome bevanda
   */
  nome: string;
  /**
   * Descrizione opzionale bevanda
   */
  descrizione?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Tipologia bevanda
   */
  tipologia: number | TipologieBevanda;
  /**
   * Nazione di produzione
   */
  nazione?: (number | null) | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-bevanda".
 */
export interface TipologieBevanda {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'user')[];
  name?: string | null;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'piatti';
        value: number | Piatti;
      } | null)
    | ({
        relationTo: 'servizi-accessori';
        value: number | ServiziAccessori;
      } | null)
    | ({
        relationTo: 'menu-fisso';
        value: number | MenuFisso;
      } | null)
    | ({
        relationTo: 'vini';
        value: number | Vini;
      } | null)
    | ({
        relationTo: 'birre';
        value: number | Birre;
      } | null)
    | ({
        relationTo: 'liquori';
        value: number | Liquori;
      } | null)
    | ({
        relationTo: 'cocktail';
        value: number | Cocktail;
      } | null)
    | ({
        relationTo: 'bevande';
        value: number | Bevande;
      } | null)
    | ({
        relationTo: 'allergeni';
        value: number | Allergeni;
      } | null)
    | ({
        relationTo: 'categoria-menu-fisso';
        value: number | CategoriaMenuFisso;
      } | null)
    | ({
        relationTo: 'categoria-piatti';
        value: number | CategoriaPiatti;
      } | null)
    | ({
        relationTo: 'tipologie-vino';
        value: number | TipologieVino;
      } | null)
    | ({
        relationTo: 'tipologie-birra';
        value: number | TipologieBirra;
      } | null)
    | ({
        relationTo: 'tipologie-liquore';
        value: number | TipologieLiquore;
      } | null)
    | ({
        relationTo: 'tipologie-cocktail';
        value: number | TipologieCocktail;
      } | null)
    | ({
        relationTo: 'tipologie-bevanda';
        value: number | TipologieBevanda;
      } | null)
    | ({
        relationTo: 'nazioni';
        value: number | Nazioni;
      } | null)
    | ({
        relationTo: 'regioni';
        value: number | Regioni;
      } | null)
    | ({
        relationTo: 'zone';
        value: number | Zone;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piatti_select".
 */
export interface PiattiSelect<T extends boolean = true> {
  inLista?: T;
  soloMenuFissi?: T;
  nome?: T;
  prezzo?: T;
  categoria?: T;
  descrizione?: T;
  glutenFree?: T;
  noUovo?: T;
  noLatticini?: T;
  vegan?: T;
  allergeni?: T;
  menuFissi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servizi-accessori_select".
 */
export interface ServiziAccessoriSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  prezzo?: T;
  descrizione?: T;
  menuFissi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-fisso_select".
 */
export interface MenuFissoSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  categoria?: T;
  prezzo?: T;
  descrizione?: T;
  piatti?: T;
  servizi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vini_select".
 */
export interface ViniSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  prezzoCalice?: T;
  tipologia?: T;
  grado?: T;
  capacita?: T;
  anno?: T;
  cantina?: T;
  certificazione?: T;
  nazione?: T;
  regione?: T;
  zona?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birre_select".
 */
export interface BirreSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  tipologia?: T;
  grado?: T;
  capacita?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liquori_select".
 */
export interface LiquoriSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  tipologia?: T;
  grado?: T;
  capacita?: T;
  invecchiamento?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail_select".
 */
export interface CocktailSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  tipologia?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bevande_select".
 */
export interface BevandeSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  tipologia?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergeni_select".
 */
export interface AllergeniSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  piatti?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-menu-fisso_select".
 */
export interface CategoriaMenuFissoSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  descrizione?: T;
  elementi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-piatti_select".
 */
export interface CategoriaPiattiSelect<T extends boolean = true> {
  inLista?: T;
  nome?: T;
  descrizione?: T;
  elementi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-vino_select".
 */
export interface TipologieVinoSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-birra_select".
 */
export interface TipologieBirraSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-liquore_select".
 */
export interface TipologieLiquoreSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-cocktail_select".
 */
export interface TipologieCocktailSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-bevanda_select".
 */
export interface TipologieBevandaSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nazioni_select".
 */
export interface NazioniSelect<T extends boolean = true> {
  nome?: T;
  sigla?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioni_select".
 */
export interface RegioniSelect<T extends boolean = true> {
  nome?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zone_select".
 */
export interface ZoneSelect<T extends boolean = true> {
  nome?: T;
  nazione?: T;
  regione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generali".
 */
export interface Generali {
  id: number;
  /**
   * Configura i 7 giorni della settimana. Ogni riga rappresenta un giorno.
   */
  scheduleWeekly?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * Il ristorante è aperto questo giorno?
         */
        isOpen?: boolean | null;
        /**
         * Aggiungi una o più fasce orarie (es. 12:00–15:00 per pranzo, 19:00–23:00 per cena).
         */
        hours?:
          | {
              start:
                | '00:00'
                | '00:15'
                | '00:30'
                | '00:45'
                | '01:00'
                | '01:15'
                | '01:30'
                | '01:45'
                | '02:00'
                | '02:15'
                | '02:30'
                | '02:45'
                | '03:00'
                | '03:15'
                | '03:30'
                | '03:45'
                | '04:00'
                | '04:15'
                | '04:30'
                | '04:45'
                | '05:00'
                | '05:15'
                | '05:30'
                | '05:45'
                | '06:00'
                | '06:15'
                | '06:30'
                | '06:45'
                | '07:00'
                | '07:15'
                | '07:30'
                | '07:45'
                | '08:00'
                | '08:15'
                | '08:30'
                | '08:45'
                | '09:00'
                | '09:15'
                | '09:30'
                | '09:45'
                | '10:00'
                | '10:15'
                | '10:30'
                | '10:45'
                | '11:00'
                | '11:15'
                | '11:30'
                | '11:45'
                | '12:00'
                | '12:15'
                | '12:30'
                | '12:45'
                | '13:00'
                | '13:15'
                | '13:30'
                | '13:45'
                | '14:00'
                | '14:15'
                | '14:30'
                | '14:45'
                | '15:00'
                | '15:15'
                | '15:30'
                | '15:45'
                | '16:00'
                | '16:15'
                | '16:30'
                | '16:45'
                | '17:00'
                | '17:15'
                | '17:30'
                | '17:45'
                | '18:00'
                | '18:15'
                | '18:30'
                | '18:45'
                | '19:00'
                | '19:15'
                | '19:30'
                | '19:45'
                | '20:00'
                | '20:15'
                | '20:30'
                | '20:45'
                | '21:00'
                | '21:15'
                | '21:30'
                | '21:45'
                | '22:00'
                | '22:15'
                | '22:30'
                | '22:45'
                | '23:00'
                | '23:15'
                | '23:30'
                | '23:45';
              end:
                | '00:00'
                | '00:15'
                | '00:30'
                | '00:45'
                | '01:00'
                | '01:15'
                | '01:30'
                | '01:45'
                | '02:00'
                | '02:15'
                | '02:30'
                | '02:45'
                | '03:00'
                | '03:15'
                | '03:30'
                | '03:45'
                | '04:00'
                | '04:15'
                | '04:30'
                | '04:45'
                | '05:00'
                | '05:15'
                | '05:30'
                | '05:45'
                | '06:00'
                | '06:15'
                | '06:30'
                | '06:45'
                | '07:00'
                | '07:15'
                | '07:30'
                | '07:45'
                | '08:00'
                | '08:15'
                | '08:30'
                | '08:45'
                | '09:00'
                | '09:15'
                | '09:30'
                | '09:45'
                | '10:00'
                | '10:15'
                | '10:30'
                | '10:45'
                | '11:00'
                | '11:15'
                | '11:30'
                | '11:45'
                | '12:00'
                | '12:15'
                | '12:30'
                | '12:45'
                | '13:00'
                | '13:15'
                | '13:30'
                | '13:45'
                | '14:00'
                | '14:15'
                | '14:30'
                | '14:45'
                | '15:00'
                | '15:15'
                | '15:30'
                | '15:45'
                | '16:00'
                | '16:15'
                | '16:30'
                | '16:45'
                | '17:00'
                | '17:15'
                | '17:30'
                | '17:45'
                | '18:00'
                | '18:15'
                | '18:30'
                | '18:45'
                | '19:00'
                | '19:15'
                | '19:30'
                | '19:45'
                | '20:00'
                | '20:15'
                | '20:30'
                | '20:45'
                | '21:00'
                | '21:15'
                | '21:30'
                | '21:45'
                | '22:00'
                | '22:15'
                | '22:30'
                | '22:45'
                | '23:00'
                | '23:15'
                | '23:30'
                | '23:45';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Intervallo di tempo in cui il ristorante serve il pranzo. Il frontend mostra il menu pranzo se l'orario corrente è compreso in questo range.
   */
  lunchSlot: {
    start:
      | '00:00'
      | '00:15'
      | '00:30'
      | '00:45'
      | '01:00'
      | '01:15'
      | '01:30'
      | '01:45'
      | '02:00'
      | '02:15'
      | '02:30'
      | '02:45'
      | '03:00'
      | '03:15'
      | '03:30'
      | '03:45'
      | '04:00'
      | '04:15'
      | '04:30'
      | '04:45'
      | '05:00'
      | '05:15'
      | '05:30'
      | '05:45'
      | '06:00'
      | '06:15'
      | '06:30'
      | '06:45'
      | '07:00'
      | '07:15'
      | '07:30'
      | '07:45'
      | '08:00'
      | '08:15'
      | '08:30'
      | '08:45'
      | '09:00'
      | '09:15'
      | '09:30'
      | '09:45'
      | '10:00'
      | '10:15'
      | '10:30'
      | '10:45'
      | '11:00'
      | '11:15'
      | '11:30'
      | '11:45'
      | '12:00'
      | '12:15'
      | '12:30'
      | '12:45'
      | '13:00'
      | '13:15'
      | '13:30'
      | '13:45'
      | '14:00'
      | '14:15'
      | '14:30'
      | '14:45'
      | '15:00'
      | '15:15'
      | '15:30'
      | '15:45'
      | '16:00'
      | '16:15'
      | '16:30'
      | '16:45'
      | '17:00'
      | '17:15'
      | '17:30'
      | '17:45'
      | '18:00'
      | '18:15'
      | '18:30'
      | '18:45'
      | '19:00'
      | '19:15'
      | '19:30'
      | '19:45'
      | '20:00'
      | '20:15'
      | '20:30'
      | '20:45'
      | '21:00'
      | '21:15'
      | '21:30'
      | '21:45'
      | '22:00'
      | '22:15'
      | '22:30'
      | '22:45'
      | '23:00'
      | '23:15'
      | '23:30'
      | '23:45';
    end:
      | '00:00'
      | '00:15'
      | '00:30'
      | '00:45'
      | '01:00'
      | '01:15'
      | '01:30'
      | '01:45'
      | '02:00'
      | '02:15'
      | '02:30'
      | '02:45'
      | '03:00'
      | '03:15'
      | '03:30'
      | '03:45'
      | '04:00'
      | '04:15'
      | '04:30'
      | '04:45'
      | '05:00'
      | '05:15'
      | '05:30'
      | '05:45'
      | '06:00'
      | '06:15'
      | '06:30'
      | '06:45'
      | '07:00'
      | '07:15'
      | '07:30'
      | '07:45'
      | '08:00'
      | '08:15'
      | '08:30'
      | '08:45'
      | '09:00'
      | '09:15'
      | '09:30'
      | '09:45'
      | '10:00'
      | '10:15'
      | '10:30'
      | '10:45'
      | '11:00'
      | '11:15'
      | '11:30'
      | '11:45'
      | '12:00'
      | '12:15'
      | '12:30'
      | '12:45'
      | '13:00'
      | '13:15'
      | '13:30'
      | '13:45'
      | '14:00'
      | '14:15'
      | '14:30'
      | '14:45'
      | '15:00'
      | '15:15'
      | '15:30'
      | '15:45'
      | '16:00'
      | '16:15'
      | '16:30'
      | '16:45'
      | '17:00'
      | '17:15'
      | '17:30'
      | '17:45'
      | '18:00'
      | '18:15'
      | '18:30'
      | '18:45'
      | '19:00'
      | '19:15'
      | '19:30'
      | '19:45'
      | '20:00'
      | '20:15'
      | '20:30'
      | '20:45'
      | '21:00'
      | '21:15'
      | '21:30'
      | '21:45'
      | '22:00'
      | '22:15'
      | '22:30'
      | '22:45'
      | '23:00'
      | '23:15'
      | '23:30'
      | '23:45';
  };
  /**
   * Intervallo di tempo in cui il ristorante serve la cena. Il frontend mostra il menu cena se l'orario corrente è compreso in questo range.
   */
  dinnerSlot: {
    start:
      | '00:00'
      | '00:15'
      | '00:30'
      | '00:45'
      | '01:00'
      | '01:15'
      | '01:30'
      | '01:45'
      | '02:00'
      | '02:15'
      | '02:30'
      | '02:45'
      | '03:00'
      | '03:15'
      | '03:30'
      | '03:45'
      | '04:00'
      | '04:15'
      | '04:30'
      | '04:45'
      | '05:00'
      | '05:15'
      | '05:30'
      | '05:45'
      | '06:00'
      | '06:15'
      | '06:30'
      | '06:45'
      | '07:00'
      | '07:15'
      | '07:30'
      | '07:45'
      | '08:00'
      | '08:15'
      | '08:30'
      | '08:45'
      | '09:00'
      | '09:15'
      | '09:30'
      | '09:45'
      | '10:00'
      | '10:15'
      | '10:30'
      | '10:45'
      | '11:00'
      | '11:15'
      | '11:30'
      | '11:45'
      | '12:00'
      | '12:15'
      | '12:30'
      | '12:45'
      | '13:00'
      | '13:15'
      | '13:30'
      | '13:45'
      | '14:00'
      | '14:15'
      | '14:30'
      | '14:45'
      | '15:00'
      | '15:15'
      | '15:30'
      | '15:45'
      | '16:00'
      | '16:15'
      | '16:30'
      | '16:45'
      | '17:00'
      | '17:15'
      | '17:30'
      | '17:45'
      | '18:00'
      | '18:15'
      | '18:30'
      | '18:45'
      | '19:00'
      | '19:15'
      | '19:30'
      | '19:45'
      | '20:00'
      | '20:15'
      | '20:30'
      | '20:45'
      | '21:00'
      | '21:15'
      | '21:30'
      | '21:45'
      | '22:00'
      | '22:15'
      | '22:30'
      | '22:45'
      | '23:00'
      | '23:15'
      | '23:30'
      | '23:45';
    end:
      | '00:00'
      | '00:15'
      | '00:30'
      | '00:45'
      | '01:00'
      | '01:15'
      | '01:30'
      | '01:45'
      | '02:00'
      | '02:15'
      | '02:30'
      | '02:45'
      | '03:00'
      | '03:15'
      | '03:30'
      | '03:45'
      | '04:00'
      | '04:15'
      | '04:30'
      | '04:45'
      | '05:00'
      | '05:15'
      | '05:30'
      | '05:45'
      | '06:00'
      | '06:15'
      | '06:30'
      | '06:45'
      | '07:00'
      | '07:15'
      | '07:30'
      | '07:45'
      | '08:00'
      | '08:15'
      | '08:30'
      | '08:45'
      | '09:00'
      | '09:15'
      | '09:30'
      | '09:45'
      | '10:00'
      | '10:15'
      | '10:30'
      | '10:45'
      | '11:00'
      | '11:15'
      | '11:30'
      | '11:45'
      | '12:00'
      | '12:15'
      | '12:30'
      | '12:45'
      | '13:00'
      | '13:15'
      | '13:30'
      | '13:45'
      | '14:00'
      | '14:15'
      | '14:30'
      | '14:45'
      | '15:00'
      | '15:15'
      | '15:30'
      | '15:45'
      | '16:00'
      | '16:15'
      | '16:30'
      | '16:45'
      | '17:00'
      | '17:15'
      | '17:30'
      | '17:45'
      | '18:00'
      | '18:15'
      | '18:30'
      | '18:45'
      | '19:00'
      | '19:15'
      | '19:30'
      | '19:45'
      | '20:00'
      | '20:15'
      | '20:30'
      | '20:45'
      | '21:00'
      | '21:15'
      | '21:30'
      | '21:45'
      | '22:00'
      | '22:15'
      | '22:30'
      | '22:45'
      | '23:00'
      | '23:15'
      | '23:30'
      | '23:45';
  };
  /**
   * Lista delle chiusure. Sovrascrivono gli orari settimanali.
   */
  exceptions?:
    | {
        /**
         * Data dell'eccezione
         */
        date: string;
        /**
         * Tipo di eccezione
         */
        type: 'chiusura-totale' | 'orario-variato';
        /**
         * Descrizione opzionale del motivo
         */
        reason?: string | null;
        /**
         * Fasce orarie speciali per questo giorno (visibile solo se il tipo è "Orario Variato").
         */
        variedHours?:
          | {
              start:
                | '00:00'
                | '00:15'
                | '00:30'
                | '00:45'
                | '01:00'
                | '01:15'
                | '01:30'
                | '01:45'
                | '02:00'
                | '02:15'
                | '02:30'
                | '02:45'
                | '03:00'
                | '03:15'
                | '03:30'
                | '03:45'
                | '04:00'
                | '04:15'
                | '04:30'
                | '04:45'
                | '05:00'
                | '05:15'
                | '05:30'
                | '05:45'
                | '06:00'
                | '06:15'
                | '06:30'
                | '06:45'
                | '07:00'
                | '07:15'
                | '07:30'
                | '07:45'
                | '08:00'
                | '08:15'
                | '08:30'
                | '08:45'
                | '09:00'
                | '09:15'
                | '09:30'
                | '09:45'
                | '10:00'
                | '10:15'
                | '10:30'
                | '10:45'
                | '11:00'
                | '11:15'
                | '11:30'
                | '11:45'
                | '12:00'
                | '12:15'
                | '12:30'
                | '12:45'
                | '13:00'
                | '13:15'
                | '13:30'
                | '13:45'
                | '14:00'
                | '14:15'
                | '14:30'
                | '14:45'
                | '15:00'
                | '15:15'
                | '15:30'
                | '15:45'
                | '16:00'
                | '16:15'
                | '16:30'
                | '16:45'
                | '17:00'
                | '17:15'
                | '17:30'
                | '17:45'
                | '18:00'
                | '18:15'
                | '18:30'
                | '18:45'
                | '19:00'
                | '19:15'
                | '19:30'
                | '19:45'
                | '20:00'
                | '20:15'
                | '20:30'
                | '20:45'
                | '21:00'
                | '21:15'
                | '21:30'
                | '21:45'
                | '22:00'
                | '22:15'
                | '22:30'
                | '22:45'
                | '23:00'
                | '23:15'
                | '23:30'
                | '23:45';
              end:
                | '00:00'
                | '00:15'
                | '00:30'
                | '00:45'
                | '01:00'
                | '01:15'
                | '01:30'
                | '01:45'
                | '02:00'
                | '02:15'
                | '02:30'
                | '02:45'
                | '03:00'
                | '03:15'
                | '03:30'
                | '03:45'
                | '04:00'
                | '04:15'
                | '04:30'
                | '04:45'
                | '05:00'
                | '05:15'
                | '05:30'
                | '05:45'
                | '06:00'
                | '06:15'
                | '06:30'
                | '06:45'
                | '07:00'
                | '07:15'
                | '07:30'
                | '07:45'
                | '08:00'
                | '08:15'
                | '08:30'
                | '08:45'
                | '09:00'
                | '09:15'
                | '09:30'
                | '09:45'
                | '10:00'
                | '10:15'
                | '10:30'
                | '10:45'
                | '11:00'
                | '11:15'
                | '11:30'
                | '11:45'
                | '12:00'
                | '12:15'
                | '12:30'
                | '12:45'
                | '13:00'
                | '13:15'
                | '13:30'
                | '13:45'
                | '14:00'
                | '14:15'
                | '14:30'
                | '14:45'
                | '15:00'
                | '15:15'
                | '15:30'
                | '15:45'
                | '16:00'
                | '16:15'
                | '16:30'
                | '16:45'
                | '17:00'
                | '17:15'
                | '17:30'
                | '17:45'
                | '18:00'
                | '18:15'
                | '18:30'
                | '18:45'
                | '19:00'
                | '19:15'
                | '19:30'
                | '19:45'
                | '20:00'
                | '20:15'
                | '20:30'
                | '20:45'
                | '21:00'
                | '21:15'
                | '21:30'
                | '21:45'
                | '22:00'
                | '22:15'
                | '22:30'
                | '22:45'
                | '23:00'
                | '23:15'
                | '23:30'
                | '23:45';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-config".
 */
export interface MenuConfig {
  id: number;
  /**
   * Ogni riga rappresenta una sezione del menu (es. "Antipasti", "Vini Rossi").
   */
  standardItems?:
    | {
        /**
         * Titolo della sezione visibile nel frontend (es. "I Nostri Primi")
         */
        label: string;
        /**
         * Collection da cui il frontend legge i dati per questa sezione
         */
        sourceCollection: (
          | 'piatti'
          | 'vini'
          | 'birre'
          | 'liquori'
          | 'cocktail'
          | 'bevande'
          | 'servizi-accessori'
          | 'menu-fisso'
        )[];
        /**
         * Disponibile solo con una singola sorgente dati. Con più sorgenti vengono mostrati tutti gli elementi.
         */
        filterMode?: ('all' | 'include' | 'exclude') | null;
        /**
         * Mostra solo le categorie/tipologie della sorgente dati selezionata.
         */
        targetCategories?:
          | (
              | {
                  relationTo: 'categoria-piatti';
                  value: number | CategoriaPiatti;
                }
              | {
                  relationTo: 'tipologie-vino';
                  value: number | TipologieVino;
                }
              | {
                  relationTo: 'tipologie-birra';
                  value: number | TipologieBirra;
                }
              | {
                  relationTo: 'tipologie-liquore';
                  value: number | TipologieLiquore;
                }
              | {
                  relationTo: 'tipologie-cocktail';
                  value: number | TipologieCocktail;
                }
              | {
                  relationTo: 'tipologie-bevanda';
                  value: number | TipologieBevanda;
                }
              | {
                  relationTo: 'categoria-menu-fisso';
                  value: number | CategoriaMenuFisso;
                }
            )[]
          | null;
        /**
         * Fascia oraria in cui mostrare questa sezione. "Solo Pranzo" e "Solo Cena" si basano sui range definiti in Generali → Fasce Pranzo/Cena.
         */
        visibility: 'always' | 'lunch_only' | 'dinner_only';
        id?: string | null;
      }[]
    | null;
  /**
   * Se abilitato e la data corrente è compresa nel range, il frontend usa specialItems al posto di standardItems.
   */
  isActive?: boolean | null;
  /**
   * Intervallo di date in cui il Menu Speciale è attivo.
   */
  activeRange?: {
    /**
     * Data di inizio del Menu Speciale (inclusa)
     */
    start?: string | null;
    /**
     * Data di fine del Menu Speciale (inclusa)
     */
    end?: string | null;
  };
  /**
   * Sezioni del menu speciale. Struttura identica al Menu Standard.
   */
  specialItems?:
    | {
        /**
         * Titolo della sezione visibile nel frontend (es. "I Nostri Primi")
         */
        label: string;
        /**
         * Collection da cui il frontend legge i dati per questa sezione
         */
        sourceCollection: (
          | 'piatti'
          | 'vini'
          | 'birre'
          | 'liquori'
          | 'cocktail'
          | 'bevande'
          | 'servizi-accessori'
          | 'menu-fisso'
        )[];
        /**
         * Disponibile solo con una singola sorgente dati. Con più sorgenti vengono mostrati tutti gli elementi.
         */
        filterMode?: ('all' | 'include' | 'exclude') | null;
        /**
         * Mostra solo le categorie/tipologie della sorgente dati selezionata.
         */
        targetCategories?:
          | (
              | {
                  relationTo: 'categoria-piatti';
                  value: number | CategoriaPiatti;
                }
              | {
                  relationTo: 'tipologie-vino';
                  value: number | TipologieVino;
                }
              | {
                  relationTo: 'tipologie-birra';
                  value: number | TipologieBirra;
                }
              | {
                  relationTo: 'tipologie-liquore';
                  value: number | TipologieLiquore;
                }
              | {
                  relationTo: 'tipologie-cocktail';
                  value: number | TipologieCocktail;
                }
              | {
                  relationTo: 'tipologie-bevanda';
                  value: number | TipologieBevanda;
                }
              | {
                  relationTo: 'categoria-menu-fisso';
                  value: number | CategoriaMenuFisso;
                }
            )[]
          | null;
        /**
         * Fascia oraria in cui mostrare questa sezione. "Solo Pranzo" e "Solo Cena" si basano sui range definiti in Generali → Fasce Pranzo/Cena.
         */
        visibility: 'always' | 'lunch_only' | 'dinner_only';
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generali_select".
 */
export interface GeneraliSelect<T extends boolean = true> {
  scheduleWeekly?:
    | T
    | {
        day?: T;
        isOpen?: T;
        hours?:
          | T
          | {
              start?: T;
              end?: T;
              id?: T;
            };
        id?: T;
      };
  lunchSlot?:
    | T
    | {
        start?: T;
        end?: T;
      };
  dinnerSlot?:
    | T
    | {
        start?: T;
        end?: T;
      };
  exceptions?:
    | T
    | {
        date?: T;
        type?: T;
        reason?: T;
        variedHours?:
          | T
          | {
              start?: T;
              end?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-config_select".
 */
export interface MenuConfigSelect<T extends boolean = true> {
  standardItems?:
    | T
    | {
        label?: T;
        sourceCollection?: T;
        filterMode?: T;
        targetCategories?: T;
        visibility?: T;
        id?: T;
      };
  isActive?: T;
  activeRange?:
    | T
    | {
        start?: T;
        end?: T;
      };
  specialItems?:
    | T
    | {
        label?: T;
        sourceCollection?: T;
        filterMode?: T;
        targetCategories?: T;
        visibility?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}