/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    piatti: Piatti;
    'servizi-accessori': ServiziAccessori;
    'menu-fisso': MenuFisso;
    vini: Vini;
    birre: Birre;
    liquori: Liquori;
    cocktail: Cocktail;
    bevande: Bevande;
    allergeni: Allergeni;
    'categoria-menu-fisso': CategoriaMenuFisso;
    'categoria-piatti': CategoriaPiatti;
    'tipologie-vino': TipologieVino;
    'tipologie-birra': TipologieBirra;
    'tipologie-liquore': TipologieLiquore;
    'tipologie-cocktail': TipologieCocktail;
    'tipologie-bevanda': TipologieBevanda;
    nazioni: Nazioni;
    regioni: Regioni;
    zone: Zone;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    piatti: PiattiSelect<false> | PiattiSelect<true>;
    'servizi-accessori': ServiziAccessoriSelect<false> | ServiziAccessoriSelect<true>;
    'menu-fisso': MenuFissoSelect<false> | MenuFissoSelect<true>;
    vini: ViniSelect<false> | ViniSelect<true>;
    birre: BirreSelect<false> | BirreSelect<true>;
    liquori: LiquoriSelect<false> | LiquoriSelect<true>;
    cocktail: CocktailSelect<false> | CocktailSelect<true>;
    bevande: BevandeSelect<false> | BevandeSelect<true>;
    allergeni: AllergeniSelect<false> | AllergeniSelect<true>;
    'categoria-menu-fisso': CategoriaMenuFissoSelect<false> | CategoriaMenuFissoSelect<true>;
    'categoria-piatti': CategoriaPiattiSelect<false> | CategoriaPiattiSelect<true>;
    'tipologie-vino': TipologieVinoSelect<false> | TipologieVinoSelect<true>;
    'tipologie-birra': TipologieBirraSelect<false> | TipologieBirraSelect<true>;
    'tipologie-liquore': TipologieLiquoreSelect<false> | TipologieLiquoreSelect<true>;
    'tipologie-cocktail': TipologieCocktailSelect<false> | TipologieCocktailSelect<true>;
    'tipologie-bevanda': TipologieBevandaSelect<false> | TipologieBevandaSelect<true>;
    nazioni: NazioniSelect<false> | NazioniSelect<true>;
    regioni: RegioniSelect<false> | RegioniSelect<true>;
    zone: ZoneSelect<false> | ZoneSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piatti".
 */
export interface Piatti {
  id: number;
  /**
   * Nome del piatto
   */
  nome: string;
  /**
   * Descrizione opzionale del piatto
   */
  descrizione?: string | null;
  /**
   * Prezzo del piatto (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se il piatto è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Se il piatto è senza glutine
   */
  glutenFree?: boolean | null;
  /**
   * Se il piatto non contiene uova
   */
  noUovo?: boolean | null;
  /**
   * Se il piatto non contiene latticini
   */
  noLatticini?: boolean | null;
  /**
   * Se il piatto è vegano
   */
  vegan?: boolean | null;
  /**
   * Se il piatto è disponibile solo nei menu fissi (non nel menu pubblico)
   */
  soloMenuFissi?: boolean | null;
  /**
   * Categoria del piatto
   */
  categoria: number | CategoriaPiatti;
  /**
   * Allergeni presenti nel piatto
   */
  allergeni?: (number | Allergeni)[] | null;
  /**
   * Menu fissi che includono questo piatto
   */
  menuFissi?: (number | MenuFisso)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-piatti".
 */
export interface CategoriaPiatti {
  id: number;
  nome: string;
  /**
   * Descrizione opzionale della categoria
   */
  descrizione?: string | null;
  /**
   * Se la categoria è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergeni".
 */
export interface Allergeni {
  id: number;
  /**
   * Nome dell'allergene (es. 'Glutine', 'Latte', 'Uova')
   */
  nome: string;
  /**
   * Descrizione opzionale dell'allergene
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-fisso".
 */
export interface MenuFisso {
  id: number;
  /**
   * Nome del menu fisso
   */
  nome: string;
  /**
   * Descrizione opzionale del menu
   */
  descrizione?: string | null;
  /**
   * Prezzo del menu fisso (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se il menu è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Categoria del menu fisso
   */
  categoria: number | CategoriaMenuFisso;
  /**
   * Piatti inclusi nel menu
   */
  piatti?: (number | Piatti)[] | null;
  /**
   * Servizi inclusi nel menu
   */
  servizi?: (number | ServiziAccessori)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-menu-fisso".
 */
export interface CategoriaMenuFisso {
  id: number;
  nome: string;
  /**
   * Descrizione opzionale della categoria
   */
  descrizione?: string | null;
  /**
   * Se la categoria è visibile nel menu
   */
  inLista?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servizi-accessori".
 */
export interface ServiziAccessori {
  id: number;
  /**
   * Nome del servizio (es. "Coperto", "Pane e Grissini")
   */
  nome: string;
  /**
   * Descrizione opzionale del servizio
   */
  descrizione?: string | null;
  /**
   * Prezzo del servizio (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se il servizio è visibile nel menu
   */
  inLista?: boolean | null;
  /**
   * Menu fissi che includono questo servizio
   */
  menuFissi?: (number | MenuFisso)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vini".
 */
export interface Vini {
  id: number;
  /**
   * Nome del vino
   */
  nome: string;
  /**
   * Descrizione opzionale del vino
   */
  descrizione?: string | null;
  /**
   * Nome della cantina produttrice
   */
  cantina?: string | null;
  /**
   * Grado alcolico (es. "13.5%", "12%")
   */
  grado?: string | null;
  /**
   * Certificazione (es. DOC, DOCG, IGT)
   */
  certificazione?: string | null;
  /**
   * Capacità della bottiglia (es. "750ml", "1L")
   */
  capacita?: string | null;
  /**
   * Prezzo per calice (max 10 cifre, 2 decimali)
   */
  prezzoCalice?: number | null;
  /**
   * Prezzo della bottiglia (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se il vino è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nazione di produzione
   */
  nazione: number | Nazioni;
  /**
   * Regione di produzione (opzionale)
   */
  regione?: (number | null) | Regioni;
  /**
   * Zona di produzione (opzionale)
   */
  zona?: (number | null) | Zone;
  /**
   * Tipologia del vino
   */
  tipologia: number | TipologieVino;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nazioni".
 */
export interface Nazioni {
  id: number;
  /**
   * Nome della nazione (es. 'Italia', 'Francia')
   */
  nome: string;
  /**
   * Sigla ISO alpha-3 (es. ITA, FRA)
   */
  sigla: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioni".
 */
export interface Regioni {
  id: number;
  /**
   * Nome della regione (es. 'Toscana', 'Piemonte')
   */
  nome: string;
  nazione: number | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zone".
 */
export interface Zone {
  id: number;
  /**
   * Nome della zona (es. 'Chianti', 'Barolo')
   */
  nome: string;
  regione: number | Regioni;
  /**
   * Per facilitare le query
   */
  nazione: number | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-vino".
 */
export interface TipologieVino {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birre".
 */
export interface Birre {
  id: number;
  /**
   * Nome della birra
   */
  nome: string;
  /**
   * Descrizione opzionale della birra
   */
  descrizione?: string | null;
  /**
   * Grado alcolico (es. "5.2%", "4.5%")
   */
  grado?: string | null;
  /**
   * Capacità (es. "33cl", "50cl", "1L")
   */
  capacita?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se la birra è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nazione di produzione
   */
  nazione: number | Nazioni;
  /**
   * Tipologia della birra
   */
  tipologia: number | TipologieBirra;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-birra".
 */
export interface TipologieBirra {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liquori".
 */
export interface Liquori {
  id: number;
  /**
   * Nome del liquore
   */
  nome: string;
  /**
   * Descrizione opzionale del liquore
   */
  descrizione?: string | null;
  /**
   * Grado alcolico (es. "40%", "35%")
   */
  grado?: string | null;
  /**
   * Invecchiamento (es. "12 anni", "8 mesi", "Non invecchiato")
   */
  invecchiamento?: string | null;
  /**
   * Capacità (es. "50ml", "70cl", "1L")
   */
  capacita?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se il liquore è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nazione di produzione
   */
  nazione: number | Nazioni;
  /**
   * Tipologia del liquore
   */
  tipologia: number | TipologieLiquore;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-liquore".
 */
export interface TipologieLiquore {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail".
 */
export interface Cocktail {
  id: number;
  /**
   * Nome del cocktail
   */
  nome: string;
  /**
   * Descrizione opzionale del cocktail
   */
  descrizione?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se il cocktail è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nazione di origine del cocktail
   */
  nazione: number | Nazioni;
  /**
   * Tipologia del cocktail
   */
  tipologia: number | TipologieCocktail;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-cocktail".
 */
export interface TipologieCocktail {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bevande".
 */
export interface Bevande {
  id: number;
  /**
   * Nome della bevanda
   */
  nome: string;
  /**
   * Descrizione opzionale della bevanda
   */
  descrizione?: string | null;
  /**
   * Prezzo (max 10 cifre, 2 decimali)
   */
  prezzo: number;
  /**
   * Se la bevanda è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  /**
   * Nazione di produzione
   */
  nazione: number | Nazioni;
  /**
   * Tipologia della bevanda
   */
  tipologia: number | TipologieBevanda;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-bevanda".
 */
export interface TipologieBevanda {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'user')[];
  name?: string | null;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'piatti';
        value: number | Piatti;
      } | null)
    | ({
        relationTo: 'servizi-accessori';
        value: number | ServiziAccessori;
      } | null)
    | ({
        relationTo: 'menu-fisso';
        value: number | MenuFisso;
      } | null)
    | ({
        relationTo: 'vini';
        value: number | Vini;
      } | null)
    | ({
        relationTo: 'birre';
        value: number | Birre;
      } | null)
    | ({
        relationTo: 'liquori';
        value: number | Liquori;
      } | null)
    | ({
        relationTo: 'cocktail';
        value: number | Cocktail;
      } | null)
    | ({
        relationTo: 'bevande';
        value: number | Bevande;
      } | null)
    | ({
        relationTo: 'allergeni';
        value: number | Allergeni;
      } | null)
    | ({
        relationTo: 'categoria-menu-fisso';
        value: number | CategoriaMenuFisso;
      } | null)
    | ({
        relationTo: 'categoria-piatti';
        value: number | CategoriaPiatti;
      } | null)
    | ({
        relationTo: 'tipologie-vino';
        value: number | TipologieVino;
      } | null)
    | ({
        relationTo: 'tipologie-birra';
        value: number | TipologieBirra;
      } | null)
    | ({
        relationTo: 'tipologie-liquore';
        value: number | TipologieLiquore;
      } | null)
    | ({
        relationTo: 'tipologie-cocktail';
        value: number | TipologieCocktail;
      } | null)
    | ({
        relationTo: 'tipologie-bevanda';
        value: number | TipologieBevanda;
      } | null)
    | ({
        relationTo: 'nazioni';
        value: number | Nazioni;
      } | null)
    | ({
        relationTo: 'regioni';
        value: number | Regioni;
      } | null)
    | ({
        relationTo: 'zone';
        value: number | Zone;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piatti_select".
 */
export interface PiattiSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  inLista?: T;
  glutenFree?: T;
  noUovo?: T;
  noLatticini?: T;
  vegan?: T;
  soloMenuFissi?: T;
  categoria?: T;
  allergeni?: T;
  menuFissi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servizi-accessori_select".
 */
export interface ServiziAccessoriSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  inLista?: T;
  menuFissi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-fisso_select".
 */
export interface MenuFissoSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  inLista?: T;
  categoria?: T;
  piatti?: T;
  servizi?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vini_select".
 */
export interface ViniSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  cantina?: T;
  grado?: T;
  certificazione?: T;
  capacita?: T;
  prezzoCalice?: T;
  prezzo?: T;
  inLista?: T;
  nazione?: T;
  regione?: T;
  zona?: T;
  tipologia?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birre_select".
 */
export interface BirreSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  grado?: T;
  capacita?: T;
  prezzo?: T;
  inLista?: T;
  nazione?: T;
  tipologia?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liquori_select".
 */
export interface LiquoriSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  grado?: T;
  invecchiamento?: T;
  capacita?: T;
  prezzo?: T;
  inLista?: T;
  nazione?: T;
  tipologia?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail_select".
 */
export interface CocktailSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  inLista?: T;
  nazione?: T;
  tipologia?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bevande_select".
 */
export interface BevandeSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  prezzo?: T;
  inLista?: T;
  nazione?: T;
  tipologia?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergeni_select".
 */
export interface AllergeniSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-menu-fisso_select".
 */
export interface CategoriaMenuFissoSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  inLista?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-piatti_select".
 */
export interface CategoriaPiattiSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  inLista?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-vino_select".
 */
export interface TipologieVinoSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-birra_select".
 */
export interface TipologieBirraSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-liquore_select".
 */
export interface TipologieLiquoreSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-cocktail_select".
 */
export interface TipologieCocktailSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-bevanda_select".
 */
export interface TipologieBevandaSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nazioni_select".
 */
export interface NazioniSelect<T extends boolean = true> {
  nome?: T;
  sigla?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioni_select".
 */
export interface RegioniSelect<T extends boolean = true> {
  nome?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zone_select".
 */
export interface ZoneSelect<T extends boolean = true> {
  nome?: T;
  regione?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}