/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    'categoria-menu-fisso': CategoriaMenuFisso;
    'categoria-piatti': CategoriaPiatti;
    allergeni: Allergeni;
    nazioni: Nazioni;
    regioni: Regioni;
    zone: Zone;
    'tipologie-vino': TipologieVino;
    'tipologie-birra': TipologieBirra;
    'tipologie-liquore': TipologieLiquore;
    'tipologie-cocktail': TipologieCocktail;
    'tipologie-bevanda': TipologieBevanda;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    'categoria-menu-fisso': CategoriaMenuFissoSelect<false> | CategoriaMenuFissoSelect<true>;
    'categoria-piatti': CategoriaPiattiSelect<false> | CategoriaPiattiSelect<true>;
    allergeni: AllergeniSelect<false> | AllergeniSelect<true>;
    nazioni: NazioniSelect<false> | NazioniSelect<true>;
    regioni: RegioniSelect<false> | RegioniSelect<true>;
    zone: ZoneSelect<false> | ZoneSelect<true>;
    'tipologie-vino': TipologieVinoSelect<false> | TipologieVinoSelect<true>;
    'tipologie-birra': TipologieBirraSelect<false> | TipologieBirraSelect<true>;
    'tipologie-liquore': TipologieLiquoreSelect<false> | TipologieLiquoreSelect<true>;
    'tipologie-cocktail': TipologieCocktailSelect<false> | TipologieCocktailSelect<true>;
    'tipologie-bevanda': TipologieBevandaSelect<false> | TipologieBevandaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-menu-fisso".
 */
export interface CategoriaMenuFisso {
  id: number;
  nome: string;
  /**
   * Descrizione opzionale della categoria
   */
  descrizione?: string | null;
  /**
   * Se la categoria è visibile nel menu
   */
  inLista?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-piatti".
 */
export interface CategoriaPiatti {
  id: number;
  nome: string;
  /**
   * Descrizione opzionale della categoria
   */
  descrizione?: string | null;
  /**
   * Se la categoria è visibile nel menu pubblico
   */
  inLista?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergeni".
 */
export interface Allergeni {
  id: number;
  /**
   * Nome dell'allergene (es. 'Glutine', 'Latte', 'Uova')
   */
  nome: string;
  /**
   * Descrizione opzionale dell'allergene
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nazioni".
 */
export interface Nazioni {
  id: number;
  /**
   * Nome della nazione (es. 'Italia', 'Francia')
   */
  nome: string;
  /**
   * Sigla ISO alpha-3 (es. ITA, FRA)
   */
  sigla: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioni".
 */
export interface Regioni {
  id: number;
  /**
   * Nome della regione (es. 'Toscana', 'Piemonte')
   */
  nome: string;
  nazione: number | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zone".
 */
export interface Zone {
  id: number;
  /**
   * Nome della zona (es. 'Chianti', 'Barolo')
   */
  nome: string;
  regione: number | Regioni;
  /**
   * Per facilitare le query
   */
  nazione: number | Nazioni;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-vino".
 */
export interface TipologieVino {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-birra".
 */
export interface TipologieBirra {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-liquore".
 */
export interface TipologieLiquore {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-cocktail".
 */
export interface TipologieCocktail {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-bevanda".
 */
export interface TipologieBevanda {
  id: number;
  nome: string;
  /**
   * Testo lungo per descrizione dettagliata
   */
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'user')[];
  name?: string | null;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categoria-menu-fisso';
        value: number | CategoriaMenuFisso;
      } | null)
    | ({
        relationTo: 'categoria-piatti';
        value: number | CategoriaPiatti;
      } | null)
    | ({
        relationTo: 'allergeni';
        value: number | Allergeni;
      } | null)
    | ({
        relationTo: 'nazioni';
        value: number | Nazioni;
      } | null)
    | ({
        relationTo: 'regioni';
        value: number | Regioni;
      } | null)
    | ({
        relationTo: 'zone';
        value: number | Zone;
      } | null)
    | ({
        relationTo: 'tipologie-vino';
        value: number | TipologieVino;
      } | null)
    | ({
        relationTo: 'tipologie-birra';
        value: number | TipologieBirra;
      } | null)
    | ({
        relationTo: 'tipologie-liquore';
        value: number | TipologieLiquore;
      } | null)
    | ({
        relationTo: 'tipologie-cocktail';
        value: number | TipologieCocktail;
      } | null)
    | ({
        relationTo: 'tipologie-bevanda';
        value: number | TipologieBevanda;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-menu-fisso_select".
 */
export interface CategoriaMenuFissoSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  inLista?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categoria-piatti_select".
 */
export interface CategoriaPiattiSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  inLista?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergeni_select".
 */
export interface AllergeniSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nazioni_select".
 */
export interface NazioniSelect<T extends boolean = true> {
  nome?: T;
  sigla?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioni_select".
 */
export interface RegioniSelect<T extends boolean = true> {
  nome?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zone_select".
 */
export interface ZoneSelect<T extends boolean = true> {
  nome?: T;
  regione?: T;
  nazione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-vino_select".
 */
export interface TipologieVinoSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-birra_select".
 */
export interface TipologieBirraSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-liquore_select".
 */
export interface TipologieLiquoreSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-cocktail_select".
 */
export interface TipologieCocktailSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tipologie-bevanda_select".
 */
export interface TipologieBevandaSelect<T extends boolean = true> {
  nome?: T;
  descrizione?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}